### ISSUE TITLE
Simplecss ownership transfer

### ISSUE THREAD

**Issue by Erithax** [linebender/simplecss#12]
The [issue](https://github.com/linebender/resvg/issues/834) regarding `resvg` ownership was closed and `resvg` was transferred to Linebender. That issue also mentioned RazrFalcon wants to transfer `simplecss`. 

I know some Linebender members are considering taking `simplecss` under Linebender too, as [mentioned ](https://xi.zulipchat.com/#narrow/channel/422907-rust-ui/topic/resvg.20looking.20for.20a.20new.20maintainer) in their Zulip. I pointed them to this issue so they can join the discussion if they want.

I'm interested in taking over maintainership of `simplecss`. This would be my first crate, but it has only 6 reverse deps, so I think that's okay. My _relevant experience_ is that I'm writing a CSS parser as part of [my CSS language server](https://github.com/erithax/csslancer).

**Comment by waywardmonkeys** [comment]
Linebender is able to host this crate as well and if we did, @Erithax or others would be welcome to help out there as well. But if someone else wants it and won’t disappear, that is fine too!

**Comment by RazrFalcon** [comment]
@Erithax no offense, but I'm looking for someone knowledgeable in Rust and with a trustworthy background, like Linebender. Giving an access to random people feels like a security nightmare to me.

You're still free to send patches, in which case there would be at least some review process.

**Comment by Erithax** [comment]
No offense taken. I totally understand that you'd rather give it to Linebender.

I just thought they maybe didn't really want it, because they currently don't depend on it.

**Comment by DJMcNab** [comment]
The reverse dependencies of simplecss include resvg, which is now under Linebender stewardship.

Fwiw, you would be welcome to maintain simplecss if it were to be moved under Linebender. That would be subject to the same review process that all maintenance within Linebender is.

**Comment by Erithax** [comment]
Oh nevermind. I didn't realize usvg was so proliferant. Then it seems like a nobrainer for Linebender to also take it.

**Comment by DJMcNab** [comment]
This is now partially complete. It looks like only @RazrFalcon has crates.io publishing permissions at the moment.
